name: Linux

on:
  push:
    branches:
      - master
      - dev
      - setup-ci
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v6

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.10.1"
          host: linux
          target: desktop
          arch: linux_gcc_64
          modules: "qtwebsockets qthttpserver"

      - name: Configure CMake
        run: cmake --preset linux

      - name: Build library
        run: cmake --build --preset linux

      - name: Build tests
        run: cmake --build --preset linux-test

      - name: Run tests
        run: ctest --preset linux
