name: MacOS

on:
  push:
    branches:
      - master
      - dev
      - setup-ci
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "5.15.2"
          host: mac
          target: desktop

      - name: Configure CMake
        run: cmake --preset macos -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=OFF -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY="-"

      - name: Build library
        run: cmake --build --preset macos

      - name: Build tests
        run: cmake --build --preset macos-test

      - name: Run tests
        run: ctest --preset macos
